#!/usr/bin/env node
/**
 * Reads API_BASE_URL from the project root .env and writes it to every app that needs it.
 *
 * Usage: npm run sync-env   (from project root)
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ROOT_ENV = path.join(ROOT, '.env');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const vars = {};
  const content = fs.readFileSync(filePath, 'utf8');

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;

    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    vars[key] = value;
  }

  return vars;
}

function upsertEnvLine(content, key, value) {
  const line = `${key}=${value}`;
  const regex = new RegExp(`^${key}=.*$`, 'm');

  if (regex.test(content)) {
    return content.replace(regex, line);
  }

  const suffix = content.endsWith('\n') || content.length === 0 ? '' : '\n';
  return `${content}${suffix}${line}\n`;
}

function normalizeBaseUrl(url) {
  return url.trim().replace(/\/$/, '');
}

function main() {
  const rootVars = parseEnvFile(ROOT_ENV);
  const apiBaseUrl = normalizeBaseUrl(rootVars.API_BASE_URL || '');

  if (!apiBaseUrl) {
    console.error('Missing API_BASE_URL in .env at project root.');
    console.error('Example: API_BASE_URL=http://192.168.1.2:8000');
    process.exit(1);
  }

  // qr-scanner/.env
  const scannerEnvPath = path.join(ROOT, 'qr-scanner', '.env');
  let scannerEnv = fs.existsSync(scannerEnvPath)
    ? fs.readFileSync(scannerEnvPath, 'utf8')
    : '';
  scannerEnv = upsertEnvLine(scannerEnv, 'EXPO_PUBLIC_API_BASE_URL', apiBaseUrl);
  fs.writeFileSync(scannerEnvPath, scannerEnv);
  console.log(`Updated qr-scanner/.env → EXPO_PUBLIC_API_BASE_URL=${apiBaseUrl}`);

  // FE/core/config.js (generated)
  const feConfigPath = path.join(ROOT, 'FE', 'core', 'config.js');
  const feApiBase = `${apiBaseUrl}/api`;
  const feConfig = `// AUTO-GENERATED by scripts/sync-env.js — do not edit manually.
// Change API_BASE_URL in the project root .env, then run: npm run sync-env
window.API_BASE = '${feApiBase}';
`;
  fs.writeFileSync(feConfigPath, feConfig);
  console.log(`Updated FE/core/config.js → window.API_BASE = '${feApiBase}'`);

  // BE2/.env → APP_URL (used for QR codes, storage URLs, emails)
  const beEnvPath = path.join(ROOT, 'BE2', '.env');
  if (fs.existsSync(beEnvPath)) {
    let beEnv = fs.readFileSync(beEnvPath, 'utf8');
    beEnv = upsertEnvLine(beEnv, 'APP_URL', apiBaseUrl);
    fs.writeFileSync(beEnvPath, beEnv);
    console.log(`Updated BE2/.env → APP_URL=${apiBaseUrl}`);
  } else {
    console.warn('Skipped BE2/.env (file not found).');
  }

  console.log('\nDone. Restart Expo if the scanner app is running.');
}

main();
